### ISSUE TITLE
Правки по ДЗ -5

### ISSUE THREAD

**Issue by Dexter19** [immortal90/dev#3]
В стилях замінити 
div {
  font-size: 1.6em;
}

span {
  font-size: 2.56em;
}

на 

div {
  font-size: 1em;
}
span {
  font-size: 1.6em;
}

**Comment by Dexter19** [comment]
В персональному сайті в 5 ДЗ розмітка має виглядадти ось так:
<nav>
        <ul>
            <li>
                <a href="contact.html">Contact</a>
            </li>
            
            <li>
                <a href="catalog.html">Catalog</a>
            </li>

            <li>
                <a href="about.html">About</a>
            </li>
        </ul>
    </nav>

    <nav>
        <a class="user" href="#" ><i class="fas fa-user"></i></a>
        <a class="cart" href="cart.html"><i class="fas fa-cart-plus"></i></a>
        <a class="like" href="#!"><i class="fas fa-heart"></i></a>
    </nav>

**Comment by Dexter19** [comment]
До персонального сайту додати всі сторінки як сказано в завданні!

**Comment by immortal90** [comment]
+ Поправив стилі
+ Додав розмітку до [Contact](https://github.com/immortal90/dev/issues/contact.html)
+ Додав до персонального сайту всі сторінки
