### ISSUE TITLE
Правки ДЗ 12

### ISSUE THREAD

**Issue by Dexter19** [immortal90/dev#4]
Зробіть копію каталога navbar

Створіть "Mobile First" media-запит, що змінює макет navbar з горизонтального меню нв вертикальне меню при переході через контрольну точку 800px.

Маэ бути х медіа запитом в такому форматі, звірте
@media screen and (min-width: 800px) {
  header {
    display: grid;
    grid-template-columns: 1fr auto minmax(600px, 3fr) 1fr auto 1fr;
  }

  nav {
    justify-content: flex-end;
    align-items: center;
    position: relative;
    display: flex;
  }
  .navbar, .toolbar{
    margin-top: 2rem;
  }

  .logo {
    grid-column: 2 / 3;
  }

  .toolbar {
    grid-column: 5 / 6;
  }

  .navbar {
    grid-column: 3 / 4;
  }

  .toolbar a{
    margin-left: .5em;
  }

  .navbar a {
    margin-left: 1em;
  }
}

**Comment by immortal90** [comment]
Поправив згідно вашого зразка
